export enum AuthOnlyTypeEnum {
    RECURRING = 'RECURRING',
    INSTALLMENTS = 'INSTALLMENTS',
    ADDCARD = 'ADDCARD',
    MAINTAINCARD = 'MAINTAINCARD',
    ACCOUNTVERIFICATION = 'ACCOUNTVERIFICATION'
}
