type PaymentOption =
    | {
          type: 'card';
          uniqueCC: string;
          threeD: Record<string, unknown>;
      }
    | {
          type: 'alternativePaymentMethod';
          externalAccountID: string;
          externalAccountDescription: string;
          externalTransactionId: string;
          APMReferenceID: string;
          orderTransactionId: string;
          paymentMethod: string;
          userPaymentOptionId: string;
      };

export interface PaymentStatusResponse {
    sessionToken?: string; // Session identifier returned by /getSessionToken or generated by /openOrder.
    version?: string; // The current version of the API method.
    status?: 'SUCCESS' | 'ERROR'; // The cashier status of a merchant request.
    transactionStatus?: string; // The Gateway transaction status.
    amount?: string; // The transaction amount.
    currency?: string; // The 3-letter ISO currency code.
    userPaymentOption?: {
        userPaymentOptionId?: string; // The first time a consumer uses a payment method, Nuvei assigns a unique ID to it. The next time the consumer uses a payment method that Nuvei has previously assigned an ID to, the ID is returned as the value of this parameter.
    };
    customData?: string; // Can be used to pass any type of information. If sent in the request, then it is passed on to the payment Gateway; it is then visible in Nuvei’s back office tool for transaction reporting and is returned in the response
    clientUniqueId?: string; // The ID of the transaction in the merchant’s system.
    gwExtendedErrorCode?: number; // Error code if error occurred on the bank side.
    gwErrorCode?: number; // The error code if error occurred.
    gwErrorReason?: string; // The error reason if error occurred at the Gateway side.
    paymentMethodErrorCode?: number; // The error code if error occurred at the APM side
    paymentMethodErrorReason?: string; // The error reason if error occurred at the APM side.
    authCode?: string; // Auth code
    merchantSiteId?: string; // The Merchant Site ID provided by Nuvei.
    transactionType?: 'Sale' | 'Auth'; // The type of transaction.
    userTokenId?: string; // This ID uniquely identifies your consumer/user in your system.
    transactionId?: string; // The Gateway transaction ID.
    errCode?: number; // The error code if the error occurred at the cashier side.
    reason?: string; // The error reason (such as “failure in checksum validation” and “timeout from processing engine”) if the error occurred at the cashier side.
    paymentOption: PaymentOption; // Represents the data retrieved from the processed payment method. It can be either card or alternativePaymentmethod.
    clientRequestId?: string; // The ID of the API request in the merchant’s system.
}
