apiVersion: v1
kind: Service
metadata:
  name: {{ include "dmn-api.fullname" . }}
  labels:
    {{- include "dmn-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - nodePort: {{ .Values.service.exposePort }}
      port: {{ .Values.service.internalPort }}
      targetPort: {{ .Values.service.targetPort }}
    # - port: {{ .Values.service.port }}
    #   targetPort: http
    #   protocol: TCP
    #   name: http
  selector:
    {{- include "dmn-api.selectorLabels" . | nindent 4 }}
